[create-payment]

req = "post"
url = "http://demo-api.airwallex.com/v1/api/payouts/create"
status = [200, 201]
body = '''
    {
        "amount": 100,
        "currency": "USD",
        "capture": true
    }'''